# $Id: Makefile,v 1.1 2003/12/09 12:43:22 dcm Exp $
#
# GSM Authentication 
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=auth_gsm.so
LIBS=-L$(LOCALBASE)/lib -L/usr/pkg/lib -lradiusclient

include ../../Makefile.modules
