# $Id: Makefile,v 1.1 2003/02/26 14:04:38 janakj Exp $
#
# uri
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=uri.so
LIBS=

include ../../Makefile.modules
