# $Id: Makefile,v 1.2 2003/03/16 18:06:42 janakj Exp $
#
# Various URI checks
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=uri.so
LIBS=

include ../../Makefile.modules

