# $Id: Makefile,v 1.4 2005/11/24 15:23:48 janakj Exp $
#
# print example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=avp.so

include ../../Makefile.modules

