# $Id: Makefile,v 1.2 2003/02/24 16:46:11 andrei Exp $
#
# print example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=radius_auth.so
DEFS += -I$(LOCALBASE)/include
LIBS=-L$(LOCALBASE)/lib -lradiusclient

include ../../Makefile.modules
