# $Id: Makefile,v 1.1 2002/09/03 14:08:41 ssi Rel $
#
# print example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=radius_auth.so
LIBS=-L/usr/local/lib -lradiusclient

include ../../Makefile.modules
