# $Id: Makefile,v 1.3 2003/03/04 14:53:53 janakj Exp $
#
# print example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=radius_auth.so
LIBS=-L/usr/local/lib -lradiusclient

include ../../Makefile.modules
