# $Id: Makefile,v 1.5 2001/12/08 22:06:27 andrei Rel $
#
# print example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=print.so
LIBS=

include ../../Makefile.modules
