# $Id: Makefile,v 1.2 2002/09/19 12:23:54 jku Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=msilo.so
LIBS=`pwd`/../im/im.so `pwd`/../tm/tm.so

include ../../Makefile.modules
