# $Id: Makefile,v 1.1 2002/08/22 18:11:59 daniel Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=msilo.so
LIBS=`pwd`/../im/im.so `pwd`/../tm/tm_mod.so

include ../../Makefile.modules
