# $Id: Makefile,v 1.1 2002/06/06 18:22:20 bogdan Rel $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=pike.so
LIBS= 

include ../../Makefile.modules
