#
# $Id: Makefile.sources,v 1.7 2002/05/13 01:15:40 jku Exp $
#
# common Makefile variables 
# (source files, objs, etc)


#
# expects: auto_gen defined
#
# defines: sources, objs, depends
#

sources=$(filter-out $(auto_gen), $(wildcard *.c) $(wildcard mem/*.c) $(wildcard parser/*.c) ) $(auto_gen)
objs=$(sources:.c=.o)
extra_objs=
depends=$(sources:.c=.d)
modules=
static_modules=
static_modules_path=
