#
# $Id: Makefile.sources,v 1.6 2002/02/20 14:57:14 andrei Exp $
#
# common Makefile variables 
# (source files, objs, etc)


#
# expects: auto_gen defined
#
# defines: sources, objs, depends
#

sources=$(filter-out $(auto_gen), $(wildcard *.c) $(wildcard mem/*.c) ) $(auto_gen)
objs=$(sources:.c=.o)
extra_objs=
depends=$(sources:.c=.d)
modules=
static_modules=
static_modules_path=
