# $Id: Makefile,v 1.1 2007/12/05 15:56:41 tirpi Exp $
#
# cfg_rpc module makefile
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=cfg_rpc.so
LIBS=

include ../../Makefile.modules
