# $Id: Makefile,v 1.1 2002/06/04 11:35:23 bogdan Rel $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=jabber.so
LIBS=`pwd`/../im/im.so

include ../../Makefile.modules
