# $Id: Makefile,v 1.3 2002/10/16 14:17:13 dcm Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=jabber.so
LIBS=-lexpat

include ../../Makefile.modules
