# $Id: Makefile,v 1.2 2005/06/01 22:25:05 andrei Exp $
#
# Digest Authentication - Diameter support
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=auth_diameter.so
#LIBS=-Llib -ldiameter_msg
#LIBS=-L$(LOCALBASE)/lib  -lradiusclient

include ../../Makefile.modules
