# $Id: Makefile,v 1.4 2003/06/23 15:38:48 bogdan Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=cpl-c.so

#DEFS +=-I/usr/include/libxml2

LIBS= -L$(LOCALBASE)/lib -L/usr/pkg/lib -lxml

include ../../Makefile.modules
