# $Id: Makefile,v 1.2 2005/12/15 23:15:53 janakj Exp $
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=xmlrpc.so
DEFS += -I/usr/include/libxml2 -I/usr/local/include/libxml2 -I/usr/local/include
LIBS +=-lxml2

include ../../Makefile.modules

