# $Id: Makefile,v 1.1 2006/02/05 19:00:39 calrissian Exp $
#
# sanity check module makefile
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs

auto_gen=
NAME=sanity.so
LIBS=

include ../../Makefile.modules
