# $Id: Makefile,v 1.1 2005/11/15 12:19:15 janakj Exp $
#
# RADIUS Accounting module
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
include ../../Makefile.radius

auto_gen=
NAME=acc_radius.so

include ../../Makefile.modules
