# $Id: Makefile,v 1.5 2002/09/30 20:02:12 andrei Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=sms.so
LIBS=

include ../../Makefile.modules
