# $Id: Makefile,v 1.1 2002/05/22 14:05:52 bogdan Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=sms.so
LIBS= 

include ../../Makefile.modules
