# $Id: Makefile,v 1.3 2002/09/20 12:52:23 bogdan Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=sms.so
LIBS=`pwd`/../im/im.so `pwd`/../tm/tm.so 

include ../../Makefile.modules
