# $Id: Makefile,v 1.2 2004/09/06 14:53:41 andrei Exp $
#
#  serunix Makefile
# 

include ../../Makefile.defs

auto_gen=
NAME=serunix


include ../../Makefile.sources
include ../../Makefile.rules


modules:
