# $Id: Makefile,v 1.3 2005/09/13 13:53:12 andrei Exp $
#
#  serunix Makefile
# 

include ../../Makefile.defs

auto_gen=
NAME=serunix
LIBS:=$(filter-out -lfl, $(LIBS) )

include ../../Makefile.sources
include ../../Makefile.rules


modules:
