# $Id: Makefile,v 1.1 2006/01/25 09:46:18 hscholz Exp $
#
# ratelimit module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs

auto_gen=
NAME=ratelimit.so

LIBS=

include ../../Makefile.modules
