# $Id: Makefile,v 1.1 2008/05/13 08:44:37 tma0 Exp $
#
# cfg_db module makefile
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=cfg_db.so
LIBS=

include ../../Makefile.modules
