# $Id: Makefile,v 1.1 2004/04/14 13:38:24 janakj Exp $
#
# Various URI checks
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=uri.so
LIBS=

include ../../Makefile.modules

