# $Id: Makefile,v 1.1 2006/06/07 09:08:39 tma0 Exp $
#
# timer module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs

auto_gen=
NAME=timer.so
LIBS=

include ../../Makefile.modules

