# $Id: Makefile,v 1.2 2003/04/18 17:58:34 andrei Exp $
#
# Group Membeship checking over Radius
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=group_radius.so
LIBS=-L$(LOCALBASE)/lib -L/usr/pkg/lib -lradiusclient

include ../../Makefile.modules
