# $Id: Makefile,v 1.1 2003/03/12 16:11:33 janakj Exp $
#
# Group Membeship checking over Radius
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=group_radius.so
LIBS=-L/usr/local/lib -lradiusclient

include ../../Makefile.modules
