# $Id: Makefile,v 1.1 2007/02/27 21:43:46 andrei Exp $
#
# dbg module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=dbg.so
LIBS=

include ../../Makefile.modules
