# $Id: Makefile,v 1.2 2003/04/18 17:58:34 andrei Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=sl.so
LIBS= 

include ../../Makefile.modules
