# $Id: Makefile,v 1.1 2002/02/12 16:48:34 bogdan Rel $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=sl.so
LIBS= #-lpthread

include ../../Makefile.modules
