# $Id: Makefile,v 1.17 2002/08/16 13:26:15 jku Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=tm_mod.so
LIBS= #-lpthread

include ../../Makefile.modules
