# $Id: Makefile,v 1.16 2001/12/08 22:06:27 andrei Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=tm.so
LIBS= #-lpthread

include ../../Makefile.modules
