# $Id: Makefile,v 1.20 2003/04/30 18:50:58 janakj Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=tm.so
LIBS=

include ../../Makefile.modules
