# $Id: Makefile,v 1.1 2008/05/12 12:14:38 janakj Exp $
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=ldap.so

#DEFS += -DLD_TEST
LIBS=-L$(LOCALBASE)/lib -L /usr/lib -lldap

include ../../Makefile.modules
