# $Id: Makefile,v 1.1 2005/11/15 12:03:52 janakj Exp $
#
# acc module makefile
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs

auto_gen=
NAME=acc_syslog.so
LIBS=

include ../../Makefile.modules
