# $Id: Makefile,v 1.1 2002/01/03 15:19:40 janakj Exp $
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=dbexample.so
LIBS=

include ../../Makefile.modules
