# $Id: Makefile,v 1.1 2006/06/07 08:38:31 tma0 Exp $
#
# db_ops module makefile
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs

auto_gen=
NAME=db_ops.so
LIBS=


include ../../Makefile.modules


