# $Id: Makefile,v 1.1 2002/08/21 20:18:11 janakj Rel $
#
# registrar module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=registrar.so
LIBS=

include ../../Makefile.modules
