/*
 * $Id $
 * 
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 */
#ifndef APPLTABLE_H
#define APPLTABLE_H

/* function declarations */
int init_applTable(void);

reg_handler init_applTable_h();
int applTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);
int snmp_registerAppl(const char *applName);

/* column number definitions for table applTable */
#define COLUMN_APPLINDEX		1
#define COLUMN_APPLNAME		2
#define COLUMN_APPLDIRECTORYNAME		3
#define COLUMN_APPLVERSION		4
#define COLUMN_APPLUPTIME		5
#define COLUMN_APPLOPERSTATUS		6
#define COLUMN_APPLLASTCHANGE		7
#define COLUMN_APPLINBOUNDASSOCIATIONS		8
#define COLUMN_APPLOUTBOUNDASSOCIATIONS		9
#define COLUMN_APPLACCUMULATEDINBOUNDASSOCIATIONS		10
#define COLUMN_APPLACCUMULATEDOUTBOUNDASSOCIATIONS		11
#define COLUMN_APPLLASTINBOUNDACTIVITY		12
#define COLUMN_APPLLASTOUTBOUNDACTIVITY		13
#define COLUMN_APPLREJECTEDINBOUNDASSOCIATIONS		14
#define COLUMN_APPLFAILEDOUTBOUNDASSOCIATIONS		15
#define COLUMN_APPLDESCRIPTION		16
#define COLUMN_APPLURL		17

#define APPLTABLE_COLUMNS 17 /* number of columns */
#define APPLTABLE_INDEXES 1	/* number of indexes */

#endif /* APPLTABLE_H */
