/*
 * $Id: applTable.h,v 1.2 2002/09/19 12:23:54 jku Rel $
 * 
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 *
 * Copyright (C) 2001-2003 Fhg Fokus
 *
 * This file is part of ser, a free SIP server.
 *
 * ser is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version
 *
 * For a license to use the ser software under conditions
 * other than those described here, or to purchase support for this
 * software, please contact iptel.org by e-mail at the following addresses:
 *    info@iptel.org
 *
 * ser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef APPLTABLE_H
#define APPLTABLE_H

/* function declarations */
int init_applTable(void);

reg_handler init_applTable_h();
int applTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);
int snmp_registerAppl(const char *applName);

/* column number definitions for table applTable */
#define COLUMN_APPLINDEX		1
#define COLUMN_APPLNAME		2
#define COLUMN_APPLDIRECTORYNAME		3
#define COLUMN_APPLVERSION		4
#define COLUMN_APPLUPTIME		5
#define COLUMN_APPLOPERSTATUS		6
#define COLUMN_APPLLASTCHANGE		7
#define COLUMN_APPLINBOUNDASSOCIATIONS		8
#define COLUMN_APPLOUTBOUNDASSOCIATIONS		9
#define COLUMN_APPLACCUMULATEDINBOUNDASSOCIATIONS		10
#define COLUMN_APPLACCUMULATEDOUTBOUNDASSOCIATIONS		11
#define COLUMN_APPLLASTINBOUNDACTIVITY		12
#define COLUMN_APPLLASTOUTBOUNDACTIVITY		13
#define COLUMN_APPLREJECTEDINBOUNDASSOCIATIONS		14
#define COLUMN_APPLFAILEDOUTBOUNDASSOCIATIONS		15
#define COLUMN_APPLDESCRIPTION		16
#define COLUMN_APPLURL		17

#define APPLTABLE_COLUMNS 17 /* number of columns */
#define APPLTABLE_INDEXES 1	/* number of indexes */

#endif /* APPLTABLE_H */
