# $Id: Makefile,v 1.1 2002/08/28 19:02:59 ric Exp $
#
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=snmp.so
CFLAGS=$(CFLAGS) `net-snmp-config --cflags`
LIBS=`net-snmp-config --agent-libs`

include ../../Makefile.modules
