/*
 * $Id: sipCommonStatusCode.h,v 1.2 2002/09/19 12:23:55 jku Rel $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 *
 * Copyright (C) 2001-2003 Fhg Fokus
 *
 * This file is part of ser, a free SIP server.
 *
 * ser is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version
 *
 * For a license to use the ser software under conditions
 * other than those described here, or to purchase support for this
 * software, please contact iptel.org by e-mail at the following addresses:
 *    info@iptel.org
 *
 * ser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef SIPCOMMONSTATUSCODE_H
#define SIPCOMMONSTATUSCODE_H

/* function declarations */
int init_sipCommonStatusCode(void);

reg_handler init_sipStatusCodesTable_h();
int sipStatusCodesTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipStatusCodesTable */
#define COLUMN_SIPSTATSINFOCLASSINS		1
#define COLUMN_SIPSTATSINFOCLASSOUTS		2
#define COLUMN_SIPSTATSSUCCESSCLASSINS		3
#define COLUMN_SIPSTATSSUCCESSCLASSOUTS		4
#define COLUMN_SIPSTATSREDIRCLASSINS		5
#define COLUMN_SIPSTATSREDIRCLASSOUTS		6
#define COLUMN_SIPSTATSREQFAILCLASSINS		7
#define COLUMN_SIPSTATSREQFAILCLASSOUTS		8
#define COLUMN_SIPSTATSSERVERFAILCLASSINS		9
#define COLUMN_SIPSTATSSERVERFAILCLASSOUTS		10
#define COLUMN_SIPSTATSGLOBALFAILCLASSINS		11
#define COLUMN_SIPSTATSGLOBALFAILCLASSOUTS		12
#define COLUMN_SIPSTATSOTHERCLASSESINS		13
#define COLUMN_SIPSTATSOTHERCLASSESOUTS		14

#define SIPSTATUSCODESTABLE_COLUMNS 14 /* number of columns */
#define SIPSTATUSCODESTABLE_INDEXES 1 /* number of indexes */

reg_handler init_sipCommonStatusCodeTable_h();
int sipCommonStatusCodeTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCommonStatusCodeTable */
#define COLUMN_SIPCOMMONSTATUSCODEVALUE		1
#define COLUMN_SIPCOMMONSTATUSCODEINS		2
#define COLUMN_SIPCOMMONSTATUSCODEOUTS		3
#define COLUMN_SIPCOMMONSTATUSCODESTATUS		4

#define SIPCOMMONSTATUSCODETABLE_COLUMNS 4 /* number of columns */
#define SIPCOMMONSTATUSCODETABLE_INDEXES 2 /* number of indexes */

#endif /* SIPCOMMONSTATUSCODE_H */
