/*
 * $Id: sipCommonCfgBase.h,v 1.1 2002/08/28 19:02:59 ric Exp $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 */
#ifndef SIPCOMMONCFGBASE_H
#define SIPCOMMONCFGBASE_H

/* function declarations */
int init_sipCommonCfgBase(void);

reg_handler init_sipCommonCfgTable_h();
int sipCommonCfgTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCommonCfgTable */
#define COLUMN_SIPPROTOCOLVERSION		1
#define COLUMN_SIPSERVICEOPERSTATUS		2
#define COLUMN_SIPSERVICEADMINSTATUS		3
#define COLUMN_SIPSERVICESTARTTIME		4
#define COLUMN_SIPSERVICELASTCHANGE		5
#define COLUMN_SIPORGANIZATION		6
#define COLUMN_SIPMAXSESSIONS		7
#define COLUMN_SIPREQUESTURIHOSTMATCHING		8

#define SIPCOMMONCFGTABLE_COLUMNS 8 /* number of columns */
#define SIPCOMMONCFGTABLE_INDEXES 1	/* number of indexes */
reg_handler init_sipUriSupportedTable_h();
int sipUriSupportedTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipUriSupportedTable */
#define COLUMN_SIPURISUPPORTEDINDEX		1
#define COLUMN_SIPURISUPPORTED		2

#define SIPURISUPPORTEDTABLE_COLUMNS 2 /* number of columns */
#define SIPURISUPPORTEDTABLE_INDEXES 2	/* number of indexes */
reg_handler init_sipFtrSupportedTable_h();
int sipFtrSupportedTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipFtrSupportedTable */
#define COLUMN_SIPFTRSUPPORTEDINDEX		1
#define COLUMN_SIPFTRSUPPORTED		2

#define SIPFTRSUPPORTEDTABLE_COLUMNS 2 /* number of columns */
#define SIPFTRSUPPORTEDTABLE_INDEXES 2	/* number of indexes */
reg_handler init_sipPortTable_h();
int sipPortTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipPortTable */
#define COLUMN_SIPPORT		1
#define COLUMN_SIPTRANSPORTRCV		2
#define COLUMN_SIPTRANSPORTSND		3
#define COLUMN_SIPPORTSTATUS		4

#define SIPPORTTABLE_COLUMNS 4 /* number of columns */
#define SIPPORTTABLE_INDEXES 2	/* number of indexes */

#endif /* SIPCOMMONCFGBASE_H */
