/*
 * $Id: sipCommonStatsTrans.h,v 1.2 2002/09/19 12:23:55 jku Rel $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 *
 * Copyright (C) 2001-2003 Fhg Fokus
 *
 * This file is part of ser, a free SIP server.
 *
 * ser is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version
 *
 * For a license to use the ser software under conditions
 * other than those described here, or to purchase support for this
 * software, please contact iptel.org by e-mail at the following addresses:
 *    info@iptel.org
 *
 * ser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef SIPCOMMONSTATSTRANS_H
#define SIPCOMMONSTATSTRANS_H

/* function declarations */
int init_sipCommonStatsTrans(void);

reg_handler init_sipCurrentTransTable_h();
int sipCurrentTransTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCurrentTransTable */
#define COLUMN_SIPCURRENTTRANSACTIONS		1

#define SIPCURRENTTRANSTABLE_COLUMNS 1 /* number of columns */
#define SIPCURRENTTRANSTABLE_INDEXES 1	/* number of indexes */
reg_handler init_sipTransactionTable_h();
int sipTransactionTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipTransactionTable */
#define COLUMN_SIPTRANSINDEX		1
#define COLUMN_SIPTRANSTO		2
#define COLUMN_SIPTRANSFROM		3
#define COLUMN_SIPTRANSCALLID		4
#define COLUMN_SIPTRANSCSEQ		5
#define COLUMN_SIPTRANSSTATE		6
#define COLUMN_SIPTRANSNUMOUTSTANDINGBRANCHES		7
#define COLUMN_SIPTRANSEXPIRY		8
#define COLUMN_SIPTRANSMETHOD		9
#define COLUMN_SIPTRANSACTIVITYINFO		10

#define SIPTRANSACTIONTABLE_COLUMNS 10 /* number of columns */
#define SIPTRANSACTIONTABLE_INDEXES 2	/* number of indexes */

#endif /* SIPCOMMONSTATSTRANS_H */
