/*
 * $Id: sipCommonCfgTable.h,v 1.1 2002/08/28 19:02:59 ric Exp $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 */
#ifndef SIPCOMMONCFGTABLE_H
#define SIPCOMMONCFGTABLE_H

/* function declarations */
int init_sipCommonCfgTable(void);

reg_handler init_sipCommonCfgTable_h();
int sipCommonCfgTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

int ser_add_sipCommonCfgTable();

/* column number definitions for table sipCommonCfgTable */
#define COLUMN_SIPPROTOCOLVERSION		1
#define COLUMN_SIPSERVICEOPERSTATUS		2
#define COLUMN_SIPSERVICEADMINSTATUS		3
#define COLUMN_SIPSERVICESTARTTIME		4
#define COLUMN_SIPSERVICELASTCHANGE		5
#define COLUMN_SIPORGANIZATION		6
#define COLUMN_SIPMAXSESSIONS		7
#define COLUMN_SIPREQUESTURIHOSTMATCHING		8

#define SIPCOMMONCFGTABLE_COLUMNS 8 /* number of columns */
#define SIPCOMMONCFGTABLE_INDEXES 1	/* number of indexes */

#endif /* SIPCOMMONCFGTABLE_H */
