/*
 * $Id: sipCommonCfgRetry.h,v 1.2 2002/09/19 12:23:54 jku Rel $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 *
 * Copyright (C) 2001-2003 Fhg Fokus
 *
 * This file is part of ser, a free SIP server.
 *
 * ser is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version
 *
 * For a license to use the ser software under conditions
 * other than those described here, or to purchase support for this
 * software, please contact iptel.org by e-mail at the following addresses:
 *    info@iptel.org
 *
 * ser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef SIPCOMMONCFGRETRY_H
#define SIPCOMMONCFGRETRY_H

/* function declarations */
int init_sipCommonCfgRetry(void);

reg_handler init_sipCommonCfgRetryTable_h();
int sipCommonCfgRetryTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCommonCfgRetryTable */
#define COLUMN_SIPCFGRETRYINVITE		1
#define COLUMN_SIPCFGRETRYBYE		2
#define COLUMN_SIPCFGRETRYCANCEL		3
#define COLUMN_SIPCFGRETRYREGISTER		4
#define COLUMN_SIPCFGRETRYOPTIONS		5
#define COLUMN_SIPCFGRETRYINFO		6
#define COLUMN_SIPCFGRETRYFINALRESPONSE		7
#define COLUMN_SIPCFGRETRYNONFINALRESPONSE		8

#define SIPCOMMONCFGRETRYTABLE_COLUMNS 8 /* number of columns */
#define SIPCOMMONCFGRETRYTABLE_INDEXES 1	/* number of indexes */
reg_handler init_sipCommonCfgRetryExtMethodTable_h();
int sipCommonCfgRetryExtMethodTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCommonCfgRetryExtMethodTable */
#define COLUMN_SIPCFGRETRYEXTMETHODINDEX		1
#define COLUMN_SIPCFGRETRYEXTMETHODNAME		2
#define COLUMN_SIPCFGRETRYEXTMETHODRETRY		3
#define COLUMN_SIPCFGRETRYEXTMETHODSTATUS		4

#define SIPCOMMONCFGRETRYEXTMETHODTABLE_COLUMNS 4 /* number of columns */
#define SIPCOMMONCFGRETRYEXTMETHODTABLE_INDEXES 2	/* number of indexes */

#endif /* SIPCOMMONCFGRETRY_H */
