/*
 * $Id: sipCommonStatsSummary.h,v 1.1 2002/08/28 19:02:59 ric Exp $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 */
#ifndef SIPCOMMONSTATSSUMMARY_H
#define SIPCOMMONSTATSSUMMARY_H

/* function declarations */
int init_sipCommonStatsSummary(void);

reg_handler init_sipSummaryStatsTable_h();
int sipSummaryStatsTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipSummaryStatsTable */
#define COLUMN_SIPSUMMARYINREQUESTS		1
#define COLUMN_SIPSUMMARYOUTREQUESTS		2
#define COLUMN_SIPSUMMARYINRESPONSES		3
#define COLUMN_SIPSUMMARYOUTRESPONSES		4
#define COLUMN_SIPSUMMARYTOTALTRANSACTIONS		5

#define SIPSUMMARYSTATSTABLE_COLUMNS 5 /* number of columns */
#define SIPSUMMARYSTATSTABLE_INDEXES 1	/* number of indexes */

#endif /* SIPCOMMONSTATSSUMMARY_H */
