/*
 * $Id: sipCommonStatsRetry.h,v 1.1 2002/08/28 19:02:59 ric Exp $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 */
#ifndef SIPCOMMONSTATSRETRY_H
#define SIPCOMMONSTATSRETRY_H

/* function declarations */
int init_sipCommonStatsRetry(void);

reg_handler init_sipCommonStatsRetryTable_h();
int sipCommonStatsRetryTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCommonStatsRetryTable */
#define COLUMN_SIPSTATSRETRYINVITES		1
#define COLUMN_SIPSTATSRETRYBYES		2
#define COLUMN_SIPSTATSRETRYCANCELS		3
#define COLUMN_SIPSTATSRETRYREGISTERS		4
#define COLUMN_SIPSTATSRETRYOPTIONS		5
#define COLUMN_SIPSTATSRETRYINFOS		6
#define COLUMN_SIPSTATSRETRYFINALRESPONSES		7
#define COLUMN_SIPSTATSRETRYNONFINALRESPONSES		8

#define SIPCOMMONSTATSRETRYTABLE_COLUMNS 8 /* number of columns */
#define SIPCOMMONSTATSRETRYTABLE_INDEXES 1	/* number of indexes */
reg_handler init_sipCommonStatsRetryExtMethodTable_h();
int sipCommonStatsRetryExtMethodTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCommonStatsRetryExtMethodTable */
#define COLUMN_SIPSTATSRETRYEXTMETHODINDEX		1
#define COLUMN_SIPSTATSRETRYEXTMETHODNAME		2
#define COLUMN_SIPSTATSRETRYEXTMETHODRETRIES		3
#define COLUMN_SIPSTATSRETRYEXTMETHODSTATUS		4

#define SIPCOMMONSTATSRETRYEXTMETHODTABLE_COLUMNS 4 /* number of columns */
#define SIPCOMMONSTATSRETRYEXTMETHODTABLE_INDEXES 2	/* number of indexes */

#endif /* SIPCOMMONSTATSRETRY_H */
