/*
 * $Id: sipCommonStatsOther.h,v 1.1 2002/08/28 19:02:59 ric Exp $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 */
#ifndef SIPCOMMONSTATSOTHER_H
#define SIPCOMMONSTATSOTHER_H

/* function declarations */
int init_sipCommonStatsOther(void);

reg_handler init_sipOtherStatsTable_h();
int sipOtherStatsTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipOtherStatsTable */
#define COLUMN_SIPNUMUNSUPPORTEDURIS		1

#define SIPOTHERSTATSTABLE_COLUMNS 1 /* number of columns */
#define SIPOTHERSTATSTABLE_INDEXES 1	/* number of indexes */

#endif /* SIPCOMMONSTATSOTHER_H */
