/*
 * $Id: sipCommonCfgExpires.h,v 1.1 2002/08/28 19:02:59 ric Exp $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 */
#ifndef SIPCOMMONCFGEXPIRES_H
#define SIPCOMMONCFGEXPIRES_H

/* function declarations */
int init_sipCommonCfgExpires(void);

reg_handler init_sipCommonCfgExpiresStatusCodeTable_h();
int sipCommonCfgExpiresStatusCodeTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCommonCfgExpiresStatusCodeTable */
#define COLUMN_SIPCFGEXPIRESSTATUSCODEVALUE		1
#define COLUMN_SIPCFGEXPIRESHEADERVALUE		2
#define COLUMN_SIPCFGEXPIRESSTATUSCODESTATUS		3

#define SIPCOMMONCFGEXPIRESSTATUSCODETABLE_COLUMNS 3 /* number of columns */
#define SIPCOMMONCFGEXPIRESSTATUSCODETABLE_INDEXES 2	/* number of indexes */
reg_handler init_sipCommonCfgExpiresMethodTable_h();
int sipCommonCfgExpiresMethodTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCommonCfgExpiresMethodTable */
#define COLUMN_SIPCFGEXPIRESINVITE		1
#define COLUMN_SIPCFGEXPIRESREGISTER		2
#define COLUMN_SIPCFGEXPIRESHEADERMETHOD		3

#define SIPCOMMONCFGEXPIRESMETHODTABLE_COLUMNS 3 /* number of columns */
#define SIPCOMMONCFGEXPIRESMETHODTABLE_INDEXES 1	/* number of indexes */

#endif /* SIPCOMMONCFGEXPIRES_H */
