/*
 * $Id: sipCommonCfgRetry.h,v 1.1 2002/08/28 19:02:59 ric Exp $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 */
#ifndef SIPCOMMONCFGRETRY_H
#define SIPCOMMONCFGRETRY_H

/* function declarations */
int init_sipCommonCfgRetry(void);

reg_handler init_sipCommonCfgRetryTable_h();
int sipCommonCfgRetryTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCommonCfgRetryTable */
#define COLUMN_SIPCFGRETRYINVITE		1
#define COLUMN_SIPCFGRETRYBYE		2
#define COLUMN_SIPCFGRETRYCANCEL		3
#define COLUMN_SIPCFGRETRYREGISTER		4
#define COLUMN_SIPCFGRETRYOPTIONS		5
#define COLUMN_SIPCFGRETRYINFO		6
#define COLUMN_SIPCFGRETRYFINALRESPONSE		7
#define COLUMN_SIPCFGRETRYNONFINALRESPONSE		8

#define SIPCOMMONCFGRETRYTABLE_COLUMNS 8 /* number of columns */
#define SIPCOMMONCFGRETRYTABLE_INDEXES 1	/* number of indexes */
reg_handler init_sipCommonCfgRetryExtMethodTable_h();
int sipCommonCfgRetryExtMethodTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCommonCfgRetryExtMethodTable */
#define COLUMN_SIPCFGRETRYEXTMETHODINDEX		1
#define COLUMN_SIPCFGRETRYEXTMETHODNAME		2
#define COLUMN_SIPCFGRETRYEXTMETHODRETRY		3
#define COLUMN_SIPCFGRETRYEXTMETHODSTATUS		4

#define SIPCOMMONCFGRETRYEXTMETHODTABLE_COLUMNS 4 /* number of columns */
#define SIPCOMMONCFGRETRYEXTMETHODTABLE_INDEXES 2	/* number of indexes */

#endif /* SIPCOMMONCFGRETRY_H */
