/*
 * $Id $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 */
#ifndef SIPCOMMONSTATUSCODE_H
#define SIPCOMMONSTATUSCODE_H

/* function declarations */
int init_sipCommonStatusCode(void);

reg_handler init_sipStatusCodesTable_h();
int sipStatusCodesTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipStatusCodesTable */
#define COLUMN_SIPSTATSINFOCLASSINS		1
#define COLUMN_SIPSTATSINFOCLASSOUTS		2
#define COLUMN_SIPSTATSSUCCESSCLASSINS		3
#define COLUMN_SIPSTATSSUCCESSCLASSOUTS		4
#define COLUMN_SIPSTATSREDIRCLASSINS		5
#define COLUMN_SIPSTATSREDIRCLASSOUTS		6
#define COLUMN_SIPSTATSREQFAILCLASSINS		7
#define COLUMN_SIPSTATSREQFAILCLASSOUTS		8
#define COLUMN_SIPSTATSSERVERFAILCLASSINS		9
#define COLUMN_SIPSTATSSERVERFAILCLASSOUTS		10
#define COLUMN_SIPSTATSGLOBALFAILCLASSINS		11
#define COLUMN_SIPSTATSGLOBALFAILCLASSOUTS		12
#define COLUMN_SIPSTATSOTHERCLASSESINS		13
#define COLUMN_SIPSTATSOTHERCLASSESOUTS		14

#define SIPSTATUSCODESTABLE_COLUMNS 14 /* number of columns */
#define SIPSTATUSCODESTABLE_INDEXES 1 /* number of indexes */

reg_handler init_sipCommonStatusCodeTable_h();
int sipCommonStatusCodeTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCommonStatusCodeTable */
#define COLUMN_SIPCOMMONSTATUSCODEVALUE		1
#define COLUMN_SIPCOMMONSTATUSCODEINS		2
#define COLUMN_SIPCOMMONSTATUSCODEOUTS		3
#define COLUMN_SIPCOMMONSTATUSCODESTATUS		4

#define SIPCOMMONSTATUSCODETABLE_COLUMNS 4 /* number of columns */
#define SIPCOMMONSTATUSCODETABLE_INDEXES 2 /* number of indexes */

#endif /* SIPCOMMONSTATUSCODE_H */
