/*
 * $Id: sipCommonCfgExpires.h,v 1.2 2002/09/19 12:23:54 jku Rel $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 *
 * Copyright (C) 2001-2003 Fhg Fokus
 *
 * This file is part of ser, a free SIP server.
 *
 * ser is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version
 *
 * For a license to use the ser software under conditions
 * other than those described here, or to purchase support for this
 * software, please contact iptel.org by e-mail at the following addresses:
 *    info@iptel.org
 *
 * ser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef SIPCOMMONCFGEXPIRES_H
#define SIPCOMMONCFGEXPIRES_H

/* function declarations */
int init_sipCommonCfgExpires(void);

reg_handler init_sipCommonCfgExpiresStatusCodeTable_h();
int sipCommonCfgExpiresStatusCodeTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCommonCfgExpiresStatusCodeTable */
#define COLUMN_SIPCFGEXPIRESSTATUSCODEVALUE		1
#define COLUMN_SIPCFGEXPIRESHEADERVALUE		2
#define COLUMN_SIPCFGEXPIRESSTATUSCODESTATUS		3

#define SIPCOMMONCFGEXPIRESSTATUSCODETABLE_COLUMNS 3 /* number of columns */
#define SIPCOMMONCFGEXPIRESSTATUSCODETABLE_INDEXES 2	/* number of indexes */
reg_handler init_sipCommonCfgExpiresMethodTable_h();
int sipCommonCfgExpiresMethodTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCommonCfgExpiresMethodTable */
#define COLUMN_SIPCFGEXPIRESINVITE		1
#define COLUMN_SIPCFGEXPIRESREGISTER		2
#define COLUMN_SIPCFGEXPIRESHEADERMETHOD		3

#define SIPCOMMONCFGEXPIRESMETHODTABLE_COLUMNS 3 /* number of columns */
#define SIPCOMMONCFGEXPIRESMETHODTABLE_INDEXES 1	/* number of indexes */

#endif /* SIPCOMMONCFGEXPIRES_H */
