/*
 * $Id: sipCommonStatsMethod.h,v 1.2 2002/09/19 12:23:54 jku Rel $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 *
 * Copyright (C) 2001-2003 Fhg Fokus
 *
 * This file is part of ser, a free SIP server.
 *
 * ser is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version
 *
 * For a license to use the ser software under conditions
 * other than those described here, or to purchase support for this
 * software, please contact iptel.org by e-mail at the following addresses:
 *    info@iptel.org
 *
 * ser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef SIPCOMMONSTATSMETHOD_H
#define SIPCOMMONSTATSMETHOD_H

/* function declarations */
int init_sipCommonStatsMethod(void);

reg_handler init_sipStatsExtMethodTable_h();
int sipStatsExtMethodTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipStatsExtMethodTable */
#define COLUMN_SIPSTATSEXTMETHODINDEX		1
#define COLUMN_SIPSTATSEXTMETHODNAME		2
#define COLUMN_SIPSTATSEXTMETHODINS		3
#define COLUMN_SIPSTATSEXTMETHODOUTS		4
#define COLUMN_SIPSTATSEXTMETHODSTATUS		5

#define SIPSTATSEXTMETHODTABLE_COLUMNS 5 /* number of columns */
#define SIPSTATSEXTMETHODTABLE_INDEXES 2	/* number of indexes */
reg_handler init_sipMethodStatsTable_h();
int sipMethodStatsTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipMethodStatsTable */
#define COLUMN_SIPSTATSINVITEINS		1
#define COLUMN_SIPSTATSINVITEOUTS		2
#define COLUMN_SIPSTATSACKINS		3
#define COLUMN_SIPSTATSACKOUTS		4
#define COLUMN_SIPSTATSBYEINS		5
#define COLUMN_SIPSTATSBYEOUTS		6
#define COLUMN_SIPSTATSCANCELINS		7
#define COLUMN_SIPSTATSCANCELOUTS		8
#define COLUMN_SIPSTATSOPTIONSINS		9
#define COLUMN_SIPSTATSOPTIONSOUTS		10
#define COLUMN_SIPSTATSREGISTERINS		11
#define COLUMN_SIPSTATSREGISTEROUTS		12
#define COLUMN_SIPSTATSINFOINS		13
#define COLUMN_SIPSTATSINFOOUTS		14

#define SIPMETHODSTATSTABLE_COLUMNS 14 /* number of columns */
#define SIPMETHODSTATSTABLE_INDEXES 1	/* number of indexes */

#endif /* SIPCOMMONSTATSMETHOD_H */
