/*
 * $Id: sipCommonStatsMethod.h,v 1.1 2002/08/28 19:02:59 ric Exp $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 */
#ifndef SIPCOMMONSTATSMETHOD_H
#define SIPCOMMONSTATSMETHOD_H

/* function declarations */
int init_sipCommonStatsMethod(void);

reg_handler init_sipStatsExtMethodTable_h();
int sipStatsExtMethodTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipStatsExtMethodTable */
#define COLUMN_SIPSTATSEXTMETHODINDEX		1
#define COLUMN_SIPSTATSEXTMETHODNAME		2
#define COLUMN_SIPSTATSEXTMETHODINS		3
#define COLUMN_SIPSTATSEXTMETHODOUTS		4
#define COLUMN_SIPSTATSEXTMETHODSTATUS		5

#define SIPSTATSEXTMETHODTABLE_COLUMNS 5 /* number of columns */
#define SIPSTATSEXTMETHODTABLE_INDEXES 2	/* number of indexes */
reg_handler init_sipMethodStatsTable_h();
int sipMethodStatsTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipMethodStatsTable */
#define COLUMN_SIPSTATSINVITEINS		1
#define COLUMN_SIPSTATSINVITEOUTS		2
#define COLUMN_SIPSTATSACKINS		3
#define COLUMN_SIPSTATSACKOUTS		4
#define COLUMN_SIPSTATSBYEINS		5
#define COLUMN_SIPSTATSBYEOUTS		6
#define COLUMN_SIPSTATSCANCELINS		7
#define COLUMN_SIPSTATSCANCELOUTS		8
#define COLUMN_SIPSTATSOPTIONSINS		9
#define COLUMN_SIPSTATSOPTIONSOUTS		10
#define COLUMN_SIPSTATSREGISTERINS		11
#define COLUMN_SIPSTATSREGISTEROUTS		12
#define COLUMN_SIPSTATSINFOINS		13
#define COLUMN_SIPSTATSINFOOUTS		14

#define SIPMETHODSTATSTABLE_COLUMNS 14 /* number of columns */
#define SIPMETHODSTATSTABLE_INDEXES 1	/* number of indexes */

#endif /* SIPCOMMONSTATSMETHOD_H */
