/*
 * $Id: sipCommonCfgTimer.h,v 1.1 2002/08/28 19:02:59 ric Exp $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 */
#ifndef SIPCOMMONCFGTIMER_H
#define SIPCOMMONCFGTIMER_H

/* function declarations */
int init_sipCommonCfgTimer(void);

reg_handler init_sipCommonCfgTimerExtMethodTable_h();
int sipCommonCfgTimerExtMethodTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCommonCfgTimerExtMethodTable */
#define COLUMN_SIPCFGTIMEREXTMETHODINDEX		1
#define COLUMN_SIPCFGTIMEREXTMETHODNAME		2
#define COLUMN_SIPCFGTIMEREXTMETHODTIMER		3
#define COLUMN_SIPCFGTIMEREXTMETHODSTATUS		4

#define SIPCOMMONCFGTIMEREXTMETHODTABLE_COLUMNS 4 /* number of columns */
#define SIPCOMMONCFGTIMEREXTMETHODTABLE_INDEXES 2	/* number of indexes */
reg_handler init_sipCommonCfgTimerTable_h();
int sipCommonCfgTimerTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipCommonCfgTimerTable */
#define COLUMN_SIPCFGINITIALTIMERINVITE		1
#define COLUMN_SIPCFGTIMERPROV		2
#define COLUMN_SIPCFGINITIALTIMERBYE		3
#define COLUMN_SIPCFGINITIALTIMERREGISTER		4
#define COLUMN_SIPCFGINITIALTIMEROPTIONS		5
#define COLUMN_SIPCFGINITIALTIMERINFO		6
#define COLUMN_SIPCFGINITIALTIMERRSP		7
#define COLUMN_SIPCFGTIMERT2		8

#define SIPCOMMONCFGTIMERTABLE_COLUMNS 8 /* number of columns */
#define SIPCOMMONCFGTIMERTABLE_INDEXES 1	/* number of indexes */

#endif /* SIPCOMMONCFGTIMER_H */
