/*
 * $Id: sipProxyCfg.h,v 1.1 2002/08/28 19:02:59 ric Exp $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 */
#ifndef SIPPROXYCFG_H
#define SIPPROXYCFG_H

/* function declarations */
int init_sipProxyCfg(void);

reg_handler init_sipProxyCfgTable_h();
int sipProxyCfgTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipProxyCfgTable */
#define COLUMN_SIPREQUESTMAXEXPIRES		1
#define COLUMN_SIPPROXYSTATEFULNESS		2
#define COLUMN_SIPPROXYSENDSCANCEL		3
#define COLUMN_SIPPROXYFORWARDALL1XX		4
#define COLUMN_SIPPROXYRECURSION		5
#define COLUMN_SIPPROXYPROVIDEALTERNATIVES		6
#define COLUMN_SIPPROXYRECORDROUTE		7
#define COLUMN_SIPPROXYSTATETIMEOUT		8
#define COLUMN_SIPPROXYAUTHMETHOD		9
#define COLUMN_SIPPROXYAUTHPGPALGORITHM		10
#define COLUMN_SIPPROXYAUTHREALM		11
#define COLUMN_SIPPROXYNONCELIFETIME		12
#define COLUMN_SIPPGPPRIVATEKEY		13

#define SIPPROXYCFGTABLE_COLUMNS 13 /* number of columns */
#define SIPPROXYCFGTABLE_INDEXES 1	/* number of indexes */

#endif /* SIPPROXYCFG_H */
