/*
 * $Id: sipProxyStats.h,v 1.1 2002/08/28 19:02:59 ric Exp $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 */
#ifndef SIPPROXYSTATS_H
#define SIPPROXYSTATS_H

/* function declarations */
int init_sipProxyStats(void);

reg_handler init_sipProxyStatsTable_h();
int sipProxyStatsTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipProxyStatsTable */
#define COLUMN_SIPNUMPROXYREQUIREFAILURES		1

#define SIPPROXYSTATSTABLE_COLUMNS 1 /* number of columns */
#define SIPPROXYSTATSTABLE_INDEXES 1	/* number of indexes */

#endif /* SIPPROXYSTATS_H */
