/*
 * $Id: sipProxyCfg.h,v 1.2 2002/09/19 12:23:55 jku Rel $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 *
 * Copyright (C) 2001-2003 Fhg Fokus
 *
 * This file is part of ser, a free SIP server.
 *
 * ser is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version
 *
 * For a license to use the ser software under conditions
 * other than those described here, or to purchase support for this
 * software, please contact iptel.org by e-mail at the following addresses:
 *    info@iptel.org
 *
 * ser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef SIPPROXYCFG_H
#define SIPPROXYCFG_H

/* function declarations */
int init_sipProxyCfg(void);

reg_handler init_sipProxyCfgTable_h();
int sipProxyCfgTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipProxyCfgTable */
#define COLUMN_SIPREQUESTMAXEXPIRES		1
#define COLUMN_SIPPROXYSTATEFULNESS		2
#define COLUMN_SIPPROXYSENDSCANCEL		3
#define COLUMN_SIPPROXYFORWARDALL1XX		4
#define COLUMN_SIPPROXYRECURSION		5
#define COLUMN_SIPPROXYPROVIDEALTERNATIVES		6
#define COLUMN_SIPPROXYRECORDROUTE		7
#define COLUMN_SIPPROXYSTATETIMEOUT		8
#define COLUMN_SIPPROXYAUTHMETHOD		9
#define COLUMN_SIPPROXYAUTHPGPALGORITHM		10
#define COLUMN_SIPPROXYAUTHREALM		11
#define COLUMN_SIPPROXYNONCELIFETIME		12
#define COLUMN_SIPPGPPRIVATEKEY		13

#define SIPPROXYCFGTABLE_COLUMNS 13 /* number of columns */
#define SIPPROXYCFGTABLE_INDEXES 1	/* number of indexes */

#endif /* SIPPROXYCFG_H */
