/*
 * $Id: sipRegCfg.h,v 1.2 2002/09/19 12:23:55 jku Rel $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 *
 * Copyright (C) 2001-2003 Fhg Fokus
 *
 * This file is part of ser, a free SIP server.
 *
 * ser is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version
 *
 * For a license to use the ser software under conditions
 * other than those described here, or to purchase support for this
 * software, please contact iptel.org by e-mail at the following addresses:
 *    info@iptel.org
 *
 * ser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef SIPREGCFG_H
#define SIPREGCFG_H

/* function declarations */
int init_sipRegCfg(void);

reg_handler init_sipRegCfgTable_h();
int sipRegCfgTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipRegCfgTable */
#define COLUMN_SIPREGALLOWTHIRDPARTY		1
#define COLUMN_SIPREGMAXCONTACTEXPIRYDATE		2
#define COLUMN_SIPREGMAXUSERS		3
#define COLUMN_SIPREGCURRENTUSERS		4
#define COLUMN_SIPREGDFLTREGACTIVEINTERVAL		5

#define SIPREGCFGTABLE_COLUMNS 5 /* number of columns */
#define SIPREGCFGTABLE_INDEXES 1	/* number of indexes */
reg_handler init_sipContactTable_h();
int sipContactTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipContactTable */
#define COLUMN_SIPCONTACTINDEX		1
#define COLUMN_SIPCONTACTDISPLAYNAME		2
#define COLUMN_SIPCONTACTURI		3
#define COLUMN_SIPCONTACTLASTUPDATED		4
#define COLUMN_SIPCONTACTEXPIRY		5
#define COLUMN_SIPCONTACTPREFERENCE		6
#define COLUMN_SIPCONTACTACTION		7
#define COLUMN_SIPCONTACTRETRYAFTER		8

#define SIPCONTACTTABLE_COLUMNS 8 /* number of columns */
#define SIPCONTACTTABLE_INDEXES 3	/* number of indexes */
reg_handler init_sipRegUserTable_h();
int sipRegUserTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipRegUserTable */
#define COLUMN_SIPUSERINDEX		1
#define COLUMN_SIPUSERURI		2
#define COLUMN_SIPUSERAUTHENTICATIONFAILURES		3
#define COLUMN_SIPUSERTABLEROWSTATUS		4

#define SIPREGUSERTABLE_COLUMNS 4 /* number of columns */
#define SIPREGUSERTABLE_INDEXES 2	/* number of indexes */

#endif /* SIPREGCFG_H */
