/*
 * $Id: sipRegCfg.h,v 1.1 2002/08/28 19:02:59 ric Exp $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 */
#ifndef SIPREGCFG_H
#define SIPREGCFG_H

/* function declarations */
int init_sipRegCfg(void);

reg_handler init_sipRegCfgTable_h();
int sipRegCfgTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipRegCfgTable */
#define COLUMN_SIPREGALLOWTHIRDPARTY		1
#define COLUMN_SIPREGMAXCONTACTEXPIRYDATE		2
#define COLUMN_SIPREGMAXUSERS		3
#define COLUMN_SIPREGCURRENTUSERS		4
#define COLUMN_SIPREGDFLTREGACTIVEINTERVAL		5

#define SIPREGCFGTABLE_COLUMNS 5 /* number of columns */
#define SIPREGCFGTABLE_INDEXES 1	/* number of indexes */
reg_handler init_sipContactTable_h();
int sipContactTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipContactTable */
#define COLUMN_SIPCONTACTINDEX		1
#define COLUMN_SIPCONTACTDISPLAYNAME		2
#define COLUMN_SIPCONTACTURI		3
#define COLUMN_SIPCONTACTLASTUPDATED		4
#define COLUMN_SIPCONTACTEXPIRY		5
#define COLUMN_SIPCONTACTPREFERENCE		6
#define COLUMN_SIPCONTACTACTION		7
#define COLUMN_SIPCONTACTRETRYAFTER		8

#define SIPCONTACTTABLE_COLUMNS 8 /* number of columns */
#define SIPCONTACTTABLE_INDEXES 3	/* number of indexes */
reg_handler init_sipRegUserTable_h();
int sipRegUserTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipRegUserTable */
#define COLUMN_SIPUSERINDEX		1
#define COLUMN_SIPUSERURI		2
#define COLUMN_SIPUSERAUTHENTICATIONFAILURES		3
#define COLUMN_SIPUSERTABLEROWSTATUS		4

#define SIPREGUSERTABLE_COLUMNS 4 /* number of columns */
#define SIPREGUSERTABLE_INDEXES 2	/* number of indexes */

#endif /* SIPREGCFG_H */
