/*
 * $Id: sipRegStats.h,v 1.1 2002/08/28 19:02:59 ric Exp $
 *
 * SNMP Module
 * 
 * Note: this file originally auto-generated by mib2c using 
 * mib2c.sipdataset.conf 
 */
#ifndef SIPREGSTATS_H
#define SIPREGSTATS_H

/* function declarations */
int init_sipRegStats(void);

reg_handler init_sipRegStatsTable_h();
int sipRegStatsTable_replaceRow(struct sip_snmp_obj *idx,
		struct sip_snmp_obj *data);

/* column number definitions for table sipRegStatsTable */
#define COLUMN_SIPREGACCEPTEDREGISTRATIONS		1
#define COLUMN_SIPREGREJECTEDREGISTRATIONS		2

#define SIPREGSTATSTABLE_COLUMNS 2 /* number of columns */
#define SIPREGSTATSTABLE_INDEXES 1	/* number of indexes */

#endif /* SIPREGSTATS_H */
