# $Id: Makefile,v 1.4 2002/03/05 14:38:46 janakj Exp $
#
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=mysql.so
LIBS=-L/usr/lib/mysql -lmysqlclient

include ../../Makefile.modules
