# $Id: Makefile,v 1.3 2002/02/24 17:11:42 janakj Exp $
#
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=mysql.so
LIBS=-lmysqlclient

include ../../Makefile.modules
