# $Id: Makefile,v 1.5 2002/04/03 21:54:15 janakj Exp $
#
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=mysql.so
LIBS=-lmysqlclient

include ../../Makefile.modules
