# $Id: Makefile,v 1.1 2006/02/23 19:57:31 andrei Exp $
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=ctl.so
LIBS=
# fifo support
DEFS+=-DUSE_FIFO

include ../../Makefile.modules

