#!/bin/sh
#
# $Id: serstat,v 1.2 2002/04/12 06:52:12 jku Exp $
#
# check current status of ser: print running processes and
# -- if in possession of MySql password -- dump USRLOC database
# as well


PIDS=`ps --no-headers -o "pid" -C sr`
for i in $PIDS ;  do
	ps -o "pid,user,group,euser,egroup,fuser,fgroup,args" $i
	echo "WD: `ls -ld /proc/$i/cwd`"
done

#ps  -wwwwww -o "drs,pid,user,group,euser,egroup,fuser,fgroup,args" -C sr 

mysql -h dbhost -u csps -p -e "select * from location;" csps107
