# $Id: Makefile,v 1.1 2006/01/06 13:29:00 janakj Exp $
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=unixsock.so
LIBS=

include ../../Makefile.modules

