=head1 NAME

ser_uri - Tool for low-level SIP URI management.

=head1 SYNOPSIS

=over 8

=item ser_uri [B<options...>] [--] B<add>       <I<uid>> <I<uri>> [I<uri> ...]

=item ser_uri [B<options...>] [--] B<canonical> <I<uid>> <I<uri>>

=item ser_uri [B<options...>] [--] B<change>    <I<uid>> <I<uri>>

=item ser_uri [B<options...>] [--] B<disable>   <I<uid>> <I<uri>>

=item ser_uri [B<options...>] [--] B<enable>    <I<uid>> <I<uri>>

=item ser_uri [B<options...>] [--] B<rm>        <I<uid>> <I<uri>>

=item ser_uri [B<options...>] [--] B<purge>

=item ser_uri [B<options...>] [--] B<show>      <I<uid>> <I<uri>>

=head1 DESCRIPTION

Command 'B<ser_uri add>' adds a new URI into SER database.

Command 'B<ser_domain change>' changes flags for I<uri> (or more precisely
given also by I<uid> and I<did>). Flags should be specified by B<-F> option.

Command 'B<ser_uri canonical>' sets URI as canonical.

Command 'B<ser_uri rm>' marks URI as deleted (set DELETED flag).

Command 'B<ser_uri disable>' sets DISABLED flag for URI.

Command 'B<ser_uri enable>' resets DISABLED flag for URI.

Command 'B<ser_uri purge>' remove all URIs marked as deleted from
database.

Command 'B<ser_uri show>' prints URIs.

=head1 OPTIONS

For options description see B<serctl>(1) man page.

=head1 SEE ALSO

Related man pages:  B<serctl>(1), B<ser_domain>(1), B<ser_uri>(1), B<ser_user>(1).

=head1 AUTHOR

Jan Halla <hallik@iptel.org>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2005, 2006 iptelorg GmbH.

This program is free software; you may redistribute it and/or modify
it under the same terms as the SIP Express Router itself.
