# $Id: Makefile,v 1.1 2002/11/22 18:40:16 bogdan Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=extcmd.so
LIBS=

include ../../Makefile.modules
