# $Id: Makefile,v 1.1 2005/12/20 11:34:26 janakj Exp $
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=fifo.so
LIBS=

include ../../Makefile.modules

