# $Id: Makefile,v 1.3 2008/06/26 10:08:03 andrei Exp $
#
#  gen_ha1 Makefile
# 

include ../../Makefile.defs

auto_gen=
NAME=gen_ha1
LIBS=../../md5.o


include ../../Makefile.sources
include ../../Makefile.targets
include ../../Makefile.rules

modules:
