#!/usr/bin/env python
# -*- encoding: UTF-8 -*-
#
# $Id: ser_db,v 1.1 2006/01/18 17:49:20 hallik Exp $
#
# Copyright (C) 2005 iptelorg GmbH
#
# This is part of SER (SIP Express Router), a free SIP server project. 
# You can redistribute it and/or modify it under the terms of GNU General
# Public License as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# Created:     2005/11/14
# Last update: 2005/11/27

from serctl.main import main
import sys

main(sys.argv)
