.TH serxmlrpc 3 2006-01-17 "" "Python serxmlrpc module. "
.SH NAME
serxmlrpc \- extension of xmlrpclib module for digest authorization and
persistent connection. Mainly for use with SER (Sip Express Router) as
client side library.
.SH SYNOPSIS
.nf
.B from serxmlrpc import *
.sp
.IB \fPclass\  Transport( uri =None, \ ssl =None)
.sp
.IB \fPexception\  UnsupportedAuthScheme( scheme )
.sp
.IB \fPfunction\  ServerProxy( uri , \ ssl =None, \ encoding =None, \ verbose =0, \ allow_none =0)
.fi
.SH DESCRIPTION
Instance of \fBTransport\fP class can be used as transport instance for \fBxmlrpc.ServerProxy\fP.
.TP
.B uri
is URI string of the form http[s]://[user[:password]@]host[:port][/path]. It is
used for making connection to server. When omited or set to None default
values are used: user='anonymous', password='', host='localhost', port=5060.
User and password are used for digest authorization.
.TP
.B ssl
is tuple of (ssl_key_file, ssl_cert_file), where ssl_key_file and ssl_cert_file are open
file handlers (file objects).
.PP
Exception
.B UnsupportedAuthScheme
is raised when server require unsupported authorization scheme.
Only digest authorization scheme supported, now.
.PP
Function
.B ServerProxy
is wrapper around ServerProxy class from xmlrpclib module. It instanties xmlrpclib.ServerProxy
with transport parameter set to new \fBTransport\fP instance. Uri and ssl
parameters are the same as described above for \fBTransport\fP. All other
parameters are directly passed to xmlrpclib.ServerProxy. See documentation
for xmlrpclib. 
.SH RETURN VALUE
ServerProxy function return xmlrpclib.ServerProxy instance.
.SH PYTHON VERSION
Module serxmlrpc is for python 2.2+. 
