# $Id: Makefile,v 1.1 2005/11/15 12:09:43 janakj Exp $
#
# acc_syslog - Accounting into syslog
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs

auto_gen=
NAME=acc_db.so
LIBS=

include ../../Makefile.modules
