# $Id: Makefile,v 1.1 2003/03/06 15:39:33 janakj Exp $
#
# Digest Authentication - Database support
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=auth_db.so
LIBS=

include ../../Makefile.modules
