# $Id: Makefile,v 1.1 2005/02/27 17:19:53 ramona Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=uac.so
LIBS= 

include ../../Makefile.modules
