# $Id: Makefile,v 1.1 2003/04/04 19:06:56 ramona Exp $
#
# print example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=pdt.so
LIBS=

include ../../Makefile.modules
