# $Id: Makefile,v 1.4 2008/07/09 20:06:32 andrei Exp $
#
# auth example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=auth.so
LIBS=
# DEFS:
#       -DUSE_NC  - compile with nounce count support
DEFS+=-DUSE_NC

include ../../Makefile.modules
