# $Id: Makefile,v 1.2 2003/02/26 14:02:19 janakj Exp $
#
# auth example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=auth.so
LIBS=

include ../../Makefile.modules
