# $Id: Makefile,v 1.1 2003/02/26 14:03:47 janakj Exp $
#
# group example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=group.so
LIBS=

include ../../Makefile.modules
