# $Id: Makefile,v 1.1 2002/11/14 14:29:48 janakj Exp $
#
# Presence Agent
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=pa.so
LIBS=

include ../../Makefile.modules
