# $Id: Makefile,v 1.3 2003/12/10 02:25:38 jamey Exp $
#
# Presence Agent
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=pa.so
LIBS=

DEFS+=-I/usr/include/libxml2
LIBS+=-I/usr/include/lib -lxml2

include ../../Makefile.modules
