# $Id: Makefile,v 1.2 2007/05/17 09:58:05 kubartv Exp $
#
# Digest Authentication - Database support
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=avp_db.so
LIBS=
DEFS += -Wall

include ../../Makefile.modules
