# $Id: Makefile,v 1.1 2002/05/10 01:04:45 jku Rel $
#
# acc module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=acc.so
LIBS=

include ../../Makefile.modules
