# $Id: Makefile,v 1.3 2001/12/08 22:06:27 andrei Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=usrloc.so
LIBS=-lmysqlclient -L/usr/lib/mysql

include ../../Makefile.modules
