# $Id: Makefile,v 1.5 2002/08/21 20:00:56 janakj Exp $
#
# registrar module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=registrar.so
LIBS=

include ../../Makefile.modules
