# $Id: Makefile,v 1.7 2002/08/21 20:09:02 janakj Rel $
#
# Usrloc module Makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=usrloc.so
LIBS=

include ../../Makefile.modules
