# $Id: Makefile,v 1.1 2002/08/19 19:40:56 jku Exp $
#
# exec module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=exec_mod.so
LIBS=

include ../../Makefile.modules
