# $Id: Makefile,v 1.1 2003/04/07 06:33:18 jiri Exp $
#
# print example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=nathelper.so
LIBS=

include ../../Makefile.modules

