# $Id: Makefile,v 1.5 2004/03/06 20:43:06 sobomax Exp $
#
# print example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=nathelper.so
LIBS=-lmd

include ../../Makefile.modules

