# $Id: Makefile,v 1.4 2003/11/06 21:22:07 bogdan Exp $
#
# print example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=nathelper.so
LIBS=

include ../../Makefile.modules

