# $Id: Makefile,v 1.1 2003/04/08 01:25:35 lgfausak Exp $
#
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=postgres.so

# libpq-fe.h locations
DEFS +=-I/usr/local/pgsql/include
LIBS=-L/usr/local/pgsql/lib -lpq

include ../../Makefile.modules
