# $Id: Makefile,v 1.2 2008/06/05 16:36:01 andrei Exp $
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=flatstore.so
LIBS=

include ../../Makefile.modules
