# $Id: Makefile,v 1.1 2004/03/21 21:00:16 danp Exp $
#
# print example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=mediaproxy.so
#DEFS+=-I../..
LIBS=

include ../../Makefile.modules

