# $Id: Makefile,v 1.1 2003/03/05 09:57:35 janakj Exp $
#
# print example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=radius_auth.so
LIBS=-L/usr/local/lib -lradiusclient

include ../../Makefile.modules
