# $Id: Makefile,v 1.7 2005/06/30 21:29:32 andrei Exp $
#
# URI checks using Radius
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
include ../../Makefile.radius

auto_gen=
NAME=uri_radius.so
LIBS=-l$(RADIUSCLIENT_LIB)

include ../../Makefile.modules
