# $Id: Makefile,v 1.1 2005/06/15 14:30:44 fgalan Exp $
#
# path module makefile
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=path.so
LIBS=


include ../../Makefile.modules
