# $Id: Makefile,v 1.6 2005/09/13 13:53:12 andrei Exp $
#
# avp_radius module Makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
include ../../Makefile.radius

auto_gen=
NAME=avp_radius.so



include ../../Makefile.modules
