# $Id: Makefile,v 1.1 2003/03/18 07:58:13 tirpi Exp $
#
# PERMISSIONS module makefile
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=permissions.so
LIBS=

include ../../Makefile.modules
