# $Id: Makefile,v 1.1 2002/01/16 10:53:12 janakj Rel $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=rr.so
LIBS=

include ../../Makefile.modules
