# $Id: Makefile,v 1.2 2003/03/31 09:39:48 janakj Exp $
#
# rr module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=rr.so
LIBS=

include ../../Makefile.modules
