# $Id: Makefile,v 1.4 2008/03/06 12:15:51 janakj Exp $
#
# rr module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=rr.so
LIBS=
SERLIBPATH=../../lib
SER_LIBS=$(SERLIBPATH)/cds/ser_cds

include ../../Makefile.modules
